services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 3
    environment:
      - POSTGRES_DB=innohassle_rooms_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

  migration:
    build: .
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DB_NAME: innohassle_rooms_api
      DB_HOST: postgres:5432
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt

volumes:
  postgres_data:
