"""Add alias field to user

Revision ID: e7cae737ebe3
Revises: af1efa064d3c
Create Date: 2024-05-13 12:39:28.632694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7cae737ebe3"
down_revision: Union[str, None] = "af1efa064d3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_invitations_addressee_alias"), "invitations", ["addressee_alias"], unique=False)
    op.add_column("users", sa.Column("alias", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_alias"), "users", ["alias"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_alias"), table_name="users")
    op.drop_column("users", "alias")
    op.drop_index(op.f("ix_invitations_addressee_alias"), table_name="invitations")
    # ### end Alembic commands ###
