"""Add fullname column to users

Revision ID: 9a560e119420
Revises: e7cae737ebe3
Create Date: 2024-05-18 15:24:21.074861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a560e119420"
down_revision: Union[str, None] = "e7cae737ebe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("fullname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "fullname")
    # ### end Alembic commands ###
