"""add expiration date to invitations

Revision ID: 02dd4f72a602
Revises: dcbfb8860b7a
Create Date: 2024-01-21 19:20:21.849046

"""

from datetime import datetime, timedelta
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02dd4f72a602"
down_revision: Union[str, None] = "dcbfb8860b7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    expiration_date = datetime.now() + timedelta(weeks=1)
    op.add_column(
        "invitations",
        sa.Column("expiration_date", sa.DateTime(), nullable=True, server_default=expiration_date.isoformat()),
    )
    op.alter_column("invitations", "expiration_date", nullable=False, server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "expiration_date")
    # ### end Alembic commands ###
