"""Use bigint in foreign user isd

Revision ID: eebf318a4b86
Revises: e7cae737ebe3
Create Date: 2024-05-17 01:06:18.213990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eebf318a4b86"
down_revision: Union[str, None] = "e7cae737ebe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "executors",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=False,
    )
    op.alter_column(
        "invitations", "sender_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invitations", "sender_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.alter_column(
        "executors",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=False,
    )
    # ### end Alembic commands ###
